[project]
name = "banking-api-qphhhs"
version = "0.1.0"
description = "Add a short description here"
authors = ["Robin Beer <r.beer@outlook.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
app = "streamlit run src/app.py"

[dependencies]
streamlit = ">=1.32.2,<1.33"
python = ">=3.12.2,<3.13"
