[project]
name = "backend"
version = "0.1.0"
description = "A banking API backend"
authors = ["Robin Beer <r.beer@outlook.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
pip_install_e = "pip install -e ."
api = "uvicorn banking_api.main:app --host 0.0.0.0 --port 8000 --reload"

[dependencies]
python = ">=3.12.2,<3.13"
fastapi = ">=0.110.0,<0.111"
pytest = ">=8.1.1,<8.2"
pip = ">=24.0,<25"
sqlmodel = ">=0.0.14,<0.1"
uvicorn = ">=0.28.0,<0.29"
httpx = ">=0.27.0,<0.28"
pytest-cov = ">=4.1.0,<4.2"
